CREATE SCHEMA IF NOT EXISTS auth;

CREATE SCHEMA IF NOT EXISTS common;

CREATE SCHEMA IF NOT EXISTS joins;

CREATE SCHEMA IF NOT EXISTS logs;

CREATE SCHEMA IF NOT EXISTS tasks;

CREATE SCHEMA IF NOT EXISTS users;
